export const ALL_PROJECTS = [
  {
    id: "skillsphere",
    title: "SkillSphere",
    desc: "A modern, full-featured online learning platform.",
    fullDesc: "SkillSphere is a comprehensive online learning platform where students can enroll in courses, track progress, and instructors can manage content. Built with a focus on performance and user experience.",
    tags: ["Next.js", "Tailwind", "MongoDB", "Better Auth", "Vercel"],
    category: "Full Stack",
    color: "#1a3a5c",
    thumbnail: "/projects/skillsphere.png",
    images: [
      "/projects/skillsphere.png",
      "/projects/skillsphere-2.png",
      "/projects/skillsphere-3.png",
    ],
    live: "https://your-live-link.com",
    gh: "https://github.com/your-repo",
    challenges: "Implementing real-time progress tracking and managing complex authentication flows across different user roles.",
    improvements: "Add video streaming, live classes, and a recommendation engine based on user learning patterns.",
  },
  {
    id: "dragon-news",
    title: "Dragon News",
    desc: "A news platform with authentication.",
    fullDesc: "Dragon News is a full-stack news platform where users can read categorized news, bookmark articles, and authenticate securely.",
    tags: ["Next.js", "Tailwind", "MongoDB", "Better Auth", "Vercel"],
    category: "Full Stack",
    color: "#1a2a3a",
    thumbnail: "/projects/dragonnews.png",
    images: [
      "/projects/dragonnews.png",
      "/projects/dragonnews-2.png",
    ],
    live: "https://your-live-link.com",
    gh: "https://github.com/your-repo",
    challenges: "Building a scalable news feed with pagination and real-time updates while maintaining fast load times.",
    improvements: "Add push notifications, personalized feed based on reading history, and a journalist dashboard.",
  },
  {
    id: "ph-app-store",
    title: "Ph-App Store",
    desc: "Innovative apps designed to make everyday life simpler.",
    fullDesc: "PH-App Store is a curated marketplace showcasing innovative apps. Users can browse, filter by category, and explore detailed app information.",
    tags: ["React", "Tailwind", "DaisyUI", "Vercel"],
    category: "Frontend",
    color: "#1a3a2a",
    thumbnail: "/projects/phappstor.png",
    images: [
      "/projects/phappstor.png",
      "/projects/phappstor-2.png",
    ],
    live: "https://your-live-link.com",
    gh: "https://github.com/your-repo",
    challenges: "Creating smooth filter animations and maintaining state across complex component hierarchies.",
    improvements: "Add user reviews, ratings system, and integrate a backend for dynamic app listings.",
  },
  {
    id: "keen-keeper",
    title: "Keen Keeper",
    desc: "Your personal shelf of meaningful connections.",
    fullDesc: "Keen Keeper helps users track and nurture their important relationships. Browse contacts, add notes, and get reminders for follow-ups.",
    tags: ["React", "Tailwind", "Context API", "Vercel"],
    category: "Frontend",
    color: "#2a2a1a",
    thumbnail: "/projects/keenkeeper.png",
    images: [
      "/projects/keenkeeper.png",
      "/projects/keenkeeper-2.png",
    ],
    live: "https://your-live-link.com",
    gh: "https://github.com/your-repo",
    challenges: "Designing an intuitive UX for relationship tracking without overwhelming the user.",
    improvements: "Add calendar integration, reminder notifications, and sync across devices.",
  },
  {
    id: "digitools",
    title: "Digitools",
    desc: "Access premium AI tools, design assets and templates.",
    fullDesc: "Digitools is a digital marketplace for premium tools including AI utilities, design assets, and productivity software.",
    tags: ["React", "Tailwind", "JavaScript ES6", "Netlify"],
    category: "Frontend",
    color: "#1a2a2a",
    thumbnail: "/projects/digitools.png",
    images: [
      "/projects/digitools.png",
      "/projects/digitools-2.png",
    ],
    live: "https://your-live-link.com",
    gh: "https://github.com/your-repo",
    challenges: "Building a performant product grid with instant search and multi-filter capabilities.",
    improvements: "Add a checkout flow, user accounts, and digital product delivery system.",
  },
  {
    id: "github-issue-tracker",
    title: "GitHub Issue Tracker",
    desc: "Track and manage your project issues efficiently.",
    fullDesc: "A GitHub Issue Tracker that connects to the GitHub API to display, filter and manage repository issues.",
    tags: ["JavaScript", "GitHub API", "CSS"],
    category: "Frontend",
    color: "#1a1a3a",
    thumbnail: "/projects/githubIssueTracker.png",
    images: [
      "/projects/githubIssueTracker.png",
    ],
    live: "https://your-live-link.com",
    gh: "https://github.com/your-repo",
    challenges: "Handling GitHub API rate limits and building a responsive issue management UI.",
    improvements: "Add PR tracking, milestone management, and team collaboration features.",
  },
  {
    id: "english-janala",
    title: "English Janala",
    desc: "An interactive platform to learn English effectively.",
    fullDesc: "English Janala is an interactive language learning app with vocabulary exercises, grammar lessons, and pronunciation guides.",
    tags: ["JavaScript", "Tailwind"],
    category: "Frontend",
    color: "#2a1a3a",
    thumbnail: "/projects/englishjanala.png",
    images: [
      "/projects/englishjanala.png",
    ],
    live: "https://your-live-link.com",
    gh: "https://github.com/your-repo",
    challenges: "Creating engaging interactive exercises that adapt to different learning levels.",
    improvements: "Add speech recognition, spaced repetition system, and progress certificates.",
  },
]